name: release

on:
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # The release type
          release-type: ruby
          # A name for the artifact releases are being created for
          # which is the name of our gem
          package-name: hopscotch
          # Should breaking changes before 1.0.0 produce minor bumps?
          bump-minor-pre-major: true
          # Path to our version file to increment
          version-file: "lib/hopscotch/version.rb"
      # Checkout code if release was created
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      # Setup ruby if a release was created
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.4
        if: ${{ steps.release.outputs.release_created }}
      # Bundle install
      - run: bundle install --jobs 4 --retry 3
        if: ${{ steps.release.outputs.release_created }}
      # Publish gem
      - uses: dawidd6/action-publish-gem@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}